// Updated: 2025-12-27
// Enhanced POS Mock Data for Service-Based Business

// Service Categories
export const serviceCategories = [
    { id: 'consulting', name: 'Consulting', icon: 'briefcase' },
    { id: 'development', name: 'Development', icon: 'code' },
    { id: 'support', name: 'Support', icon: 'headphones' },
    { id: 'training', name: 'Training', icon: 'graduation-cap' },
    { id: 'maintenance', name: 'Maintenance', icon: 'wrench' },
];

// Services with enhanced details
export const services = [
    {
        id: 'SVC-001',
        name: 'Business Consulting',
        sku: 'CONS-BUS-001',
        description: 'Strategic business consultation and planning',
        category: 'consulting',
        type: 'hourly',
        price: 2500,
        duration: '1 Hour',
        taxRate: 18,
        sacCode: '998314',
        isActive: true,
    },
    {
        id: 'SVC-002',
        name: 'Web Development',
        sku: 'DEV-WEB-001',
        description: 'Custom website development and design',
        category: 'development',
        type: 'fixed',
        price: 50000,
        duration: '2 Weeks',
        taxRate: 18,
        sacCode: '998313',
        isActive: true,
    },
    {
        id: 'SVC-003',
        name: 'Technical Support',
        sku: 'SUP-TECH-001',
        description: 'Remote technical support and troubleshooting',
        category: 'support',
        type: 'hourly',
        price: 1500,
        duration: '1 Hour',
        taxRate: 18,
        sacCode: '998315',
        isActive: true,
    },
    {
        id: 'SVC-004',
        name: 'Software Training',
        sku: 'TRN-SOFT-001',
        description: 'On-site or online software training sessions',
        category: 'training',
        type: 'fixed',
        price: 15000,
        duration: '1 Day',
        taxRate: 18,
        sacCode: '999293',
        isActive: true,
    },
    {
        id: 'SVC-005',
        name: 'System Maintenance',
        sku: 'MNT-SYS-001',
        description: 'Monthly system maintenance and updates',
        category: 'maintenance',
        type: 'fixed',
        price: 8000,
        duration: 'Monthly',
        taxRate: 18,
        sacCode: '998316',
        isActive: true,
    },
    {
        id: 'SVC-006',
        name: 'IT Consulting',
        sku: 'CONS-IT-001',
        description: 'IT infrastructure and strategy consultation',
        category: 'consulting',
        type: 'hourly',
        price: 3000,
        duration: '1 Hour',
        taxRate: 18,
        sacCode: '998314',
        isActive: true,
    },
];

// Clients with complete details
export const clients = [
    {
        id: 'CLT-001',
        name: 'Acme Corporation',
        email: 'contact@acmecorp.com',
        phone: '+91 98765 43210',
        gstin: '29AAAAA0000A1Z5',
        address: '123 Business Park',
        city: 'Bangalore',
        state: 'Karnataka',
        pincode: '560001',
        balance: 0,
        totalSpent: 125000,
        lastVisit: '2024-12-26',
        notes: 'Premium client, monthly retainer',
        createdAt: '2024-01-15',
    },
    {
        id: 'CLT-002',
        name: 'Tech Solutions Pvt Ltd',
        email: 'info@techsolutions.in',
        phone: '+91 98765 43211',
        gstin: '27BBBBB1111B2Z6',
        address: '456 Tech Tower',
        city: 'Mumbai',
        state: 'Maharashtra',
        pincode: '400001',
        balance: 15000,
        totalSpent: 85000,
        lastVisit: '2024-12-25',
        notes: 'Quarterly support contract',
        createdAt: '2024-02-20',
    },
    {
        id: 'CLT-003',
        name: 'Walk-in Client',
        email: '',
        phone: '',
        gstin: '',
        address: '',
        city: '',
        state: '',
        pincode: '',
        balance: 0,
        totalSpent: 0,
        lastVisit: null,
        notes: 'Default walk-in customer',
        createdAt: '2024-01-01',
    },
];

// Invoices with detailed structure
export const invoices = [
    {
        id: 'INV-001',
        invoiceNumber: 'INV-2024-001',
        date: '2024-12-27T10:30:00',
        dueDate: '2025-01-10',
        clientId: 'CLT-001',
        client: clients[0],
        items: [
            {
                serviceId: 'SVC-001',
                name: 'Business Consulting',
                description: 'Q4 Strategy Planning',
                sacCode: '998314',
                quantity: 4,
                rate: 2500,
                amount: 10000,
                taxRate: 18,
                taxAmount: 1800,
            },
            {
                serviceId: 'SVC-004',
                name: 'Software Training',
                description: 'Team training session',
                sacCode: '999293',
                quantity: 1,
                rate: 15000,
                amount: 15000,
                taxRate: 18,
                taxAmount: 2700,
            },
        ],
        subtotal: 25000,
        discount: 1000,
        taxTotal: 4320,
        total: 28320,
        amountPaid: 28320,
        balance: 0,
        status: 'paid',
        paymentMethod: 'Bank Transfer',
        sessionId: 'SES-001',
        notes: 'Payment received via NEFT',
        createdAt: '2024-12-27T10:30:00',
        updatedAt: '2024-12-27T11:00:00',
    },
];

// Cash Sessions
export const sessions = [
    {
        id: 'SES-001',
        userId: 'admin',
        userName: 'Admin User',
        openedAt: '2024-12-27T09:00:00',
        closedAt: '2024-12-27T18:00:00',
        openingCash: 5000,
        closingCash: 15000,
        expectedCash: 15200,
        variance: -200,
        totalSales: 45000,
        invoiceCount: 12,
        status: 'closed',
    },
    {
        id: 'SES-002',
        userId: 'admin',
        userName: 'Admin User',
        openedAt: '2024-12-27T09:00:00',
        closedAt: null,
        openingCash: 5000,
        closingCash: null,
        expectedCash: null,
        variance: null,
        totalSales: 28320,
        invoiceCount: 1,
        status: 'open',
    },
];

// Payment Methods
export const paymentMethods = [
    { id: 'cash', name: 'Cash', icon: 'banknote' },
    { id: 'card', name: 'Card', icon: 'credit-card' },
    { id: 'upi', name: 'UPI', icon: 'smartphone' },
    { id: 'bank', name: 'Bank Transfer', icon: 'building' },
    { id: 'cheque', name: 'Cheque', icon: 'file-text' },
];

// Company Details (for invoices)
export const companyDetails = {
    name: 'Novotion Tech Solutions LLP',
    address: '123 Tech Park, MG Road',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560001',
    gstin: '29ABCDE1234F1Z5',
    pan: 'ABCDE1234F',
    phone: '+91 80 1234 5678',
    email: 'billing@novotion.com',
    website: 'www.novotion.com',
    bankName: 'HDFC Bank',
    accountNumber: '50200012345678',
    ifscCode: 'HDFC0001234',
    branch: 'MG Road, Bangalore',
};
